### PR TITLE
Fixed issue in Writer

### PR DESCRIPTION
**Pull request by illishar**
Fixed issue in next_segment calculation. (Also altered some of the helper function. Not really that relevant though.)

### CODE REVIEW

**Comment by winggndm** [comment]
I tested this with a single segment and it worked.  I'm having an issue with appending multiple segments.  From what I remember, you should be able to binary append files together and it should work.  So after closing the first segment i tried:

f = new WriteSegment(stream);
f.BaseStream.Seek(0, System.IO.SeekOrigin.End);

repeated inserting data and close again.  The issue is that the data length is being interpreted wrong when reading with the excel importer from NI

Both segments were 10,000 samples 

The file seems to have the right information of there being 10000 samples in each channel

image

but excel shows a weird split of 16666 and 13333

image

**Comment by winggndm** [comment]
found the issue, seems that property wf_samples is required for it to work correctly so GenerateStandardChannel should include it:

            if (increment != 0) meta.Properties.Add("wf_increment", increment);
            **meta.Properties.Add("wf_samples", dataCount);**
            meta.RawData = new Reader.RawData();

once i I added  that i was able to make a generic function to handle writing for any data type and the file can be read correctly in Excel as well as Labview

**Comment by illishar** [comment]
Nice

**Comment by winggndm** [comment]
I did some further testing trying to find the minimum properties required to be set, and it seems that
1) There is no minimum property required other than Group and Channel name
2) Certain properties require other properties to be set

wf_samples seems to be required either because wf_start_time or wf_increment is set, or possibly both. If i remove all properties other than group name and name, then file can be read correctly also. 

image

When Labview TDMSwrite writes a waveform, it writes the group name, and channel name and the the following minimum properties
wf_increment
wf_samples
wf_start_offset
wf_start_time

When TDMSWrite writes an array, it just writes the group name and channel name, no other properties

Hope this helps

**Comment by illishar** [comment]
It seems that you also have to set the "ContainsNewObjects" bit, in order for programs like Signal.X Scout, to work. (It could be made in a default, I guess.)

**Comment by winggndm** [comment]
When I was checking the files LabView made, I also saw that flag set each, so It would be a good idea to do.

**Comment by mikeobrien** [comment]
Sorry for the delay! Thx for the PR!

**Comment by mikeobrien** [comment]
@winggndm, @illishar would either one of you be interested in being added as a collaborator so you can push to master without a PR? My life is crazy busy right now so dont have the time to keep up with this repo.

**Comment by illishar** [comment]
Sure, you can add me.

**Pull request merged**
