### PR TITLE
Support parsing a TDMS when only stream is available

### PR DESCRIPTION
**Pull request by bazwilliams**
We store TDMS files in a MongoDb and our service needs to read them out and convert on the fly. This pull request adds support for using a Stream directly avoiding the need to save the TDMS to a temp folder and read back in.

### CODE REVIEW

**Comment by mikeobrien** [comment]
So I ended up wanting to implement this a little differently than the PR proposed. The functionality is in c6cef668c2ef36907463ed767b59cb09131121e2 and pushed to nuget. Couple of things to note:

 - `File` now has a constructor overload that takes a `Stream`.
 - `File` now implements `IDisposable` so you'll want to make sure either this is disposed or the underlying stream is disposed.
 - Supports seekable streams only.

Can you give me a little more info on enumerating all the metadata? It's been awhile since I originally worked on this so I'm thinking I set it up that way for a reason but can't remember at this point.

**Comment by bazwilliams** [comment]
Much prefer your implementation in c6cef66 to my pragmatic version. Thanks, I'll try this on Monday. 

The metadata issue was a fix because I had a TDMS file which I had 3 properties I needed to use, but 1 of the properties appeared to be in a different metadata object. I.e. 2 metadata objects, 1 with 2 properties and the other with 1. When debugging I could see it in the list of all metadata, but because of the line which prioritises the metadata item with the highest count of properties I couldn't use it in my calculations. 

I never checked the offending TDMS file in as part of a test as it wasn't mine to publish, I'll find out in work on Monday and send you it if you are interested.

**Comment by mikeobrien** [comment]
Ok, cool. I'll take a look at the [spec](https://github.com/mikeobrien/TDMSReader/blob/master/misc/TDMSFileFormatInternalStructure.pdf) when I get a minute to see what it says about the metadata.

**Comment by mikeobrien** [comment]
Aight, v3.0.12.0 is out on nuget. Thx for the PR!

**Comment by bazwilliams** [comment]
No worries - thanks for fast turnaround! New nuget package works a treat.

**Pull request closed without merging**
